# Generated by Django 4.0.6 on 2022-11-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_playboardmanage_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiwinmanage',
            old_name='winLoseDate',
            new_name='winLoseData',
        ),
    ]
