# Generated by Django 4.0.6 on 2022-11-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiLoseManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(auto_now_add=True, verbose_name='対局日')),
                ('file_path', models.CharField(blank=True, max_length=100, verbose_name='ファイルパス')),
                ('width', models.IntegerField(verbose_name='width')),
                ('height', models.IntegerField(verbose_name='height')),
            ],
        ),
        migrations.CreateModel(
            name='AiWinManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winLoseDate', models.CharField(max_length=10, verbose_name='AIの勝ち負け')),
            ],
        ),
        migrations.CreateModel(
            name='PlayBoardMange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(verbose_name='width')),
                ('height', models.IntegerField(verbose_name='height')),
            ],
        ),
    ]
