# Generated by Django 4.0.6 on 2022-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playboardmanage',
            name='winner',
            field=models.CharField(blank=True, max_length=5, verbose_name='winner'),
        ),
    ]
