# Generated by Django 4.0.6 on 2022-11-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_playboardmanage_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playboardmanage',
            name='winner',
            field=models.CharField(max_length=5, null=True, verbose_name='winner'),
        ),
    ]
